version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: stori-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: 0.0.0.0
    ports:
      - "5432:5432"
    volumes:
      - stori-postgres-data:/var/lib/postgresql/data

volumes:
  stori-postgres-data:
